In [11]:
import torch
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print("Size",x.size())
print("Shape",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size torch.Size([3, 3])
Shape torch.Size([3, 3])
랭크(차원): 2


In [12]:
x = torch.unsqueeze(x,0)
print(x)
print("Size",x.size())
print("Shape",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size torch.Size([1, 3, 3])
Shape torch.Size([1, 3, 3])
랭크(차원): 3


In [13]:
x = torch.squeeze(x,0)
print(x)
print("Size",x.size())
print("Shape",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size torch.Size([3, 3])
Shape torch.Size([3, 3])
랭크(차원): 2


In [14]:
x = x.view(9)
print(x)
print("Size",x.size())
print("Shape",x.shape)
print("랭크(차원):",x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size torch.Size([9])
Shape torch.Size([9])
랭크(차원): 1


SyntaxError: invalid syntax (<ipython-input-15-b72edafd3056>, line 1)